### ISSUE TITLE
Handle configuration rows

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/tech-radar#13]
Contained within the spreadsheets that we intend to display, we want to include an extra column `configvalue`. 

If this column is a null value, then we count that row as data that ought to be visualised, otherwise, we take the content of this row to be a configuration option. The key for configuration parameter will be the content of the name column, and the value for this key will be the value of the `configvalue` column for this row.

**Comment by AdaRoseCannon** [comment]
I'll configure this so that they become the default but don't override the auery params.

**Comment by AdaRoseCannon** [comment]
Fixed
