### ISSUE TITLE
allow for a band to be empty, but still displayed in the view

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/tech-radar#41]
This could be configured via the data, with an item row only having a value for the field which is being used to define the bands. The item would not be displayed, but it would ensure a band with that value is displayed, even if there are no other items with that band's value.

e.g. if we specify sortcol=tech1 (from the example spreadsheet), and add an extra row to the data sheet which only has a value in the tech1 column, "toast", then the additional band called toast will be displayed, with no items in it.

**Comment by AdaRoseCannon** [comment]
Done, if you set sortcol order to have bands with no content they will still be included.
